In [3]:
import pandas as pd
import csv

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB

In [5]:
df = pd.read_csv('Test.csv')

In [11]:
X = df['Article_content']
Y = df['type']

In [12]:
Y

0          dengue
1          dengue
2          dengue
3          dengue
4          dengue
5          dengue
6          dengue
7          dengue
8          dengue
9          dengue
10         dengue
11         dengue
12         dengue
13         dengue
14         dengue
15         dengue
16         dengue
17         dengue
18         dengue
19         dengue
20         dengue
21         dengue
22         dengue
23         dengue
24         dengue
25         dengue
26         dengue
27         dengue
28         dengue
29         dengue
          ...    
961    non-dengue
962    non-dengue
963    non-dengue
964    non-dengue
965    non-dengue
966    non-dengue
967    non-dengue
968    non-dengue
969    non-dengue
970    non-dengue
971    non-dengue
972    non-dengue
973    non-dengue
974    non-dengue
975    non-dengue
976    non-dengue
977    non-dengue
978    non-dengue
979    non-dengue
980    non-dengue
981    non-dengue
982    non-dengue
983    non-dengue
984    non-dengue
985    non

In [7]:
X = X.fillna("")

In [8]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
Y = le.fit_transform(Y.astype(str))

In [9]:
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

In [7]:
from sklearn.model_selection import cross_val_score

In [9]:
from sklearn.pipeline import Pipeline

In [142]:
text_clf = Pipeline([('vect', CountVectorizer()), ('tfidf', TfidfTransformer()), ('clf', MultinomialNB())])

In [63]:
scores = cross_val_score(text_clf, X, Y, cv=10, scoring='accuracy')

In [64]:
scores

array([ 0.88      ,  0.92      ,  0.90909091,  0.86868687,  0.88888889,
        0.84848485,  0.92929293,  0.82828283,  0.78787879,  0.85714286])

In [65]:
scores.mean()

0.87177489177489176

In [66]:
from sklearn.model_selection import GridSearchCV
param_grid = {'vect__ngram_range': [(1, 1), (1, 2)], 'tfidf__use_idf': (True, False), 'clf__alpha': (1e-2, 1e-3)}

In [67]:
# instantiate and fit the grid
grid = GridSearchCV(text_clf, param_grid, cv=10, scoring='accuracy', return_train_score=False)
grid.fit(X, Y)

GridSearchCV(cv=10, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip...inear_tf=False, use_idf=True)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))]),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'vect__ngram_range': [(1, 1), (1, 2)], 'tfidf__use_idf': (True, False), 'clf__alpha': (0.01, 0.001)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
       scoring='accuracy', verbose=0)

In [68]:
# view the results
pd.DataFrame(grid.cv_results_)[['mean_test_score', 'std_test_score', 'params']]

mean_test_score  std_test_score  \
0         0.889001        0.031280   
1         0.887992        0.026142   
2         0.898083        0.029271   
3         0.897074        0.027802   
4         0.876892        0.027739   
5         0.883956        0.035445   
6         0.890010        0.027919   
7         0.895055        0.026840   

                                              params  
0  {'clf__alpha': 0.01, 'tfidf__use_idf': True, '...  
1  {'clf__alpha': 0.01, 'tfidf__use_idf': True, '...  
2  {'clf__alpha': 0.01, 'tfidf__use_idf': False, ...  
3  {'clf__alpha': 0.01, 'tfidf__use_idf': False, ...  
4  {'clf__alpha': 0.001, 'tfidf__use_idf': True, ...  
5  {'clf__alpha': 0.001, 'tfidf__use_idf': True, ...  
6  {'clf__alpha': 0.001, 'tfidf__use_idf': False,...  
7  {'clf__alpha': 0.001, 'tfidf__use_idf': False,...

In [69]:
# examine the best model
print(grid.best_score_)
print(grid.best_params_)

0.898082744702
{'clf__alpha': 0.01, 'tfidf__use_idf': False, 'vect__ngram_range': (1, 1)}


In [70]:
from sklearn.linear_model import SGDClassifier

In [71]:
text_clf_svm = Pipeline([('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                         ('clf-svm', SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3, max_iter=5, random_state=42))])

In [72]:
%time scores = cross_val_score(text_clf_svm, X, Y, cv=10, scoring='accuracy')

Wall time: 4.63 s


In [73]:
scores

array([ 0.93      ,  0.95      ,  0.90909091,  0.87878788,  0.91919192,
        0.8989899 ,  0.96969697,  0.86868687,  0.93939394,  0.84693878])

In [74]:
scores.mean()

0.91107771593485865

In [75]:
param_grid_svm = {'vect__ngram_range': [(1, 1), (1, 2)], 'tfidf__use_idf': (True, False),
                  'clf-svm__alpha': (1e-2, 1e-3)}

In [76]:
grid = GridSearchCV(text_clf_svm, param_grid_svm, cv=10, scoring='accuracy', return_train_score=False)
grid.fit(X, Y)

GridSearchCV(cv=10, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip...ty='l2', power_t=0.5, random_state=42, shuffle=True,
       tol=None, verbose=0, warm_start=False))]),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'vect__ngram_range': [(1, 1), (1, 2)], 'tfidf__use_idf': (True, False), 'clf-svm__alpha': (0.01, 0.001)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
       scoring='accuracy', verbose=0)

In [77]:
# view the results
pd.DataFrame(grid.cv_results_)[['mean_test_score', 'std_test_score', 'params']]

mean_test_score  std_test_score  \
0         0.867810        0.047671   
1         0.852674        0.059235   
2         0.854692        0.049524   
3         0.850656        0.056120   
4         0.911201        0.036393   
5         0.899092        0.041716   
6         0.907164        0.044761   
7         0.910192        0.039345   

                                              params  
0  {'clf-svm__alpha': 0.01, 'tfidf__use_idf': Tru...  
1  {'clf-svm__alpha': 0.01, 'tfidf__use_idf': Tru...  
2  {'clf-svm__alpha': 0.01, 'tfidf__use_idf': Fal...  
3  {'clf-svm__alpha': 0.01, 'tfidf__use_idf': Fal...  
4  {'clf-svm__alpha': 0.001, 'tfidf__use_idf': Tr...  
5  {'clf-svm__alpha': 0.001, 'tfidf__use_idf': Tr...  
6  {'clf-svm__alpha': 0.001, 'tfidf__use_idf': Fa...  
7  {'clf-svm__alpha': 0.001, 'tfidf__use_idf': Fa...

In [78]:
# examine the best model
print(grid.best_score_)
print(grid.best_params_)

0.911200807265
{'clf-svm__alpha': 0.001, 'tfidf__use_idf': True, 'vect__ngram_range': (1, 1)}


In [30]:
text_clf = Pipeline([('vect', CountVectorizer(stop_words='english')), ('tfidf', TfidfTransformer()),('clf', MultinomialNB())])

In [31]:
%time scores = cross_val_score(text_clf, X, Y, cv=10, scoring='accuracy')

Wall time: 4.22 s


In [32]:
scores.mean()

0.87987590187590181

In [79]:
grid = GridSearchCV(text_clf, param_grid, cv=10, scoring='accuracy', return_train_score=False)
grid.fit(X, Y)

GridSearchCV(cv=10, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip...inear_tf=False, use_idf=True)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))]),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'vect__ngram_range': [(1, 1), (1, 2)], 'tfidf__use_idf': (True, False), 'clf__alpha': (0.01, 0.001)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
       scoring='accuracy', verbose=0)

In [80]:
print(grid.best_score_)
print(grid.best_params_)

0.898082744702
{'clf__alpha': 0.01, 'tfidf__use_idf': False, 'vect__ngram_range': (1, 1)}


In [84]:
text_clf_svm = Pipeline([('vect', CountVectorizer(stop_words='english')), ('tfidf', TfidfTransformer()),
                         ('clf-svm', SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3, max_iter=5, random_state=42))])

In [85]:
%time scores = cross_val_score(text_clf_svm, X, Y, cv=10, scoring='accuracy')

Wall time: 4.18 s


In [86]:
scores

array([ 0.94      ,  0.94      ,  0.90909091,  0.91919192,  0.91919192,
        0.90909091,  0.96969697,  0.90909091,  0.93939394,  0.89795918])

In [87]:
scores.mean()

0.92527066584209439

In [88]:
grid = GridSearchCV(text_clf_svm, param_grid_svm, cv=10, scoring='accuracy', return_train_score=False)
grid.fit(X, Y)

GridSearchCV(cv=10, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words='english',
        ...ty='l2', power_t=0.5, random_state=42, shuffle=True,
       tol=None, verbose=0, warm_start=False))]),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'vect__ngram_range': [(1, 1), (1, 2)], 'tfidf__use_idf': (True, False), 'clf-svm__alpha': (0.01, 0.001)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
       scoring='accuracy', verbose=0)

In [89]:
print(grid.best_score_)
print(grid.best_params_)

0.953582240161
{'clf-svm__alpha': 0.001, 'tfidf__use_idf': False, 'vect__ngram_range': (1, 1)}


In [90]:
import nltk
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("english", ignore_stopwords=True)

In [91]:
class StemmedCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(StemmedCountVectorizer, self).build_analyzer()
        return lambda doc: ([stemmer.stem(w) for w in analyzer(doc)])

In [92]:
stemmed_count_vect = StemmedCountVectorizer(stop_words='english')

In [98]:
text_mnb_stemmed = Pipeline([('vect', stemmed_count_vect), ('tfidf', TfidfTransformer()),
                             ('clf', MultinomialNB(fit_prior=False))])

In [99]:
%time scores = cross_val_score(text_mnb_stemmed, X, Y, cv=10, scoring='accuracy')

Wall time: 53.4 s


In [95]:
scores

array([ 0.89      ,  0.88      ,  0.8989899 ,  0.86868687,  0.84848485,
        0.85858586,  0.93939394,  0.87878788,  0.80808081,  0.85714286])

In [100]:
scores.mean()

0.87281529581529593

In [101]:
param_grid = {'vect__ngram_range': [(1, 1), (1, 2)], 'tfidf__use_idf': (True, False), 'clf__alpha': (1e-2, 1e-3)}

In [102]:
grid = GridSearchCV(text_mnb_stemmed, param_grid, cv=10, scoring='accuracy', return_train_score=False)
grid.fit(X, Y)

GridSearchCV(cv=10, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('vect', StemmedCountVectorizer(analyzer='word', binary=False, decode_error='strict',
            dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
            lowercase=True, max_df=1.0, max_features=None, min_df=1,
            ngram_range=(1, 1), preprocessor=None, stop_words=...near_tf=False, use_idf=True)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=False))]),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'vect__ngram_range': [(1, 1), (1, 2)], 'tfidf__use_idf': (True, False), 'clf__alpha': (0.01, 0.001)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
       scoring='accuracy', verbose=0)

In [103]:
print(grid.best_score_)
print(grid.best_params_)

0.91019172553
{'clf__alpha': 0.01, 'tfidf__use_idf': False, 'vect__ngram_range': (1, 2)}


In [104]:
text_clf_svm = Pipeline([('vect', stemmed_count_vect), ('tfidf', TfidfTransformer()),
                         ('clf-svm', SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3, max_iter=5, random_state=42))])

In [105]:
%time scores = cross_val_score(text_clf_svm, X, Y, cv=10, scoring='accuracy')

Wall time: 55.2 s


In [106]:
scores

array([ 0.94      ,  0.96      ,  0.91919192,  0.91919192,  0.92929293,
        0.8989899 ,  0.96969697,  0.87878788,  0.95959596,  0.92857143])

In [107]:
scores.mean()

0.93033189033189045

In [108]:
grid = GridSearchCV(text_clf_svm, param_grid_svm, cv=10, scoring='accuracy', return_train_score=False)
grid.fit(X, Y)

GridSearchCV(cv=10, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('vect', StemmedCountVectorizer(analyzer='word', binary=False, decode_error='strict',
            dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
            lowercase=True, max_df=1.0, max_features=None, min_df=1,
            ngram_range=(1, 1), preprocessor=None, stop_words=...ty='l2', power_t=0.5, random_state=42, shuffle=True,
       tol=None, verbose=0, warm_start=False))]),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'vect__ngram_range': [(1, 1), (1, 2)], 'tfidf__use_idf': (True, False), 'clf-svm__alpha': (0.01, 0.001)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
       scoring='accuracy', verbose=0)

In [109]:
print(grid.best_score_)
print(grid.best_params_)

0.945509586276
{'clf-svm__alpha': 0.001, 'tfidf__use_idf': False, 'vect__ngram_range': (1, 1)}


In [110]:
# from nltk.stem.porter import *

In [111]:
# stemmer = PorterStemmer()

In [125]:
# stemmer = SnowballStemmer("porter")

In [126]:
# class StemmedCountVectorizer(CountVectorizer):
#     def build_analyzer(self):
#         analyzer = super(StemmedCountVectorizer, self).build_analyzer()
#         return lambda doc: ([stemmer.stem(w) for w in analyzer(doc)])

In [127]:
# stemmed_count_vect = StemmedCountVectorizer(stop_words='english')

In [128]:
# text_mnb_stemmed = Pipeline([('vect', stemmed_count_vect), ('tfidf', TfidfTransformer()),
#                              ('clf', MultinomialNB(fit_prior=False))])

In [129]:
# %time scores = cross_val_score(text_mnb_stemmed, X, Y, cv=10, scoring='accuracy')

Wall time: 1min 12s


In [130]:
# scores.mean()

0.87281529581529593

In [51]:
from sklearn.model_selection import GridSearchCV
param_grid = {'vect__ngram_range': [(1, 1), (1, 2)], 'tfidf__use_idf': (True, False), 'clf__alpha': (1e-2, 1e-3)}

In [54]:
# instantiate and fit the grid
grid = GridSearchCV(text_clf, param_grid, cv=10, scoring='accuracy', return_train_score=False)
grid.fit(X, Y)

GridSearchCV(cv=10, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words='english',
        ...inear_tf=False, use_idf=True)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))]),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'vect__ngram_range': [(1, 1), (1, 2)], 'tfidf__use_idf': (True, False), 'clf__alpha': (0.01, 0.001)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
       scoring='accuracy', verbose=0)

In [55]:
# view the results
pd.DataFrame(grid.cv_results_)[['mean_test_score', 'std_test_score', 'params']]

mean_test_score  std_test_score  \
0         0.891019        0.026366   
1         0.902119        0.023358   
2         0.903128        0.024428   
3         0.909183        0.023882   
4         0.870838        0.027386   
5         0.890010        0.028567   
6         0.885974        0.031850   
7         0.898083        0.025214   

                                              params  
0  {'clf__alpha': 0.01, 'tfidf__use_idf': True, '...  
1  {'clf__alpha': 0.01, 'tfidf__use_idf': True, '...  
2  {'clf__alpha': 0.01, 'tfidf__use_idf': False, ...  
3  {'clf__alpha': 0.01, 'tfidf__use_idf': False, ...  
4  {'clf__alpha': 0.001, 'tfidf__use_idf': True, ...  
5  {'clf__alpha': 0.001, 'tfidf__use_idf': True, ...  
6  {'clf__alpha': 0.001, 'tfidf__use_idf': False,...  
7  {'clf__alpha': 0.001, 'tfidf__use_idf': False,...

In [56]:
# examine the best model
print(grid.best_score_)
print(grid.best_params_)

0.909182643794
{'clf__alpha': 0.01, 'tfidf__use_idf': False, 'vect__ngram_range': (1, 2)}


In [57]:
parameters_svm = {'vect__ngram_range': [(1, 1), (1, 2)], 'tfidf__use_idf': (True, False),
                  'clf-svm__alpha': (1e-2, 1e-3)}

In [59]:
grid = GridSearchCV(text_clf_svm, parameters_svm, cv=10, scoring='accuracy', return_train_score=False)
grid.fit(X, Y)

GridSearchCV(cv=10, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('vect', StemmedCountVectorizer(analyzer='word', binary=False, decode_error='strict',
            dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
            lowercase=True, max_df=1.0, max_features=None, min_df=1,
            ngram_range=(1, 1), preprocessor=None, stop_words=...ty='l2', power_t=0.5, random_state=42, shuffle=True,
       tol=None, verbose=0, warm_start=False))]),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'vect__ngram_range': [(1, 1), (1, 2)], 'tfidf__use_idf': (True, False), 'clf-svm__alpha': (0.01, 0.001)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
       scoring='accuracy', verbose=0)

In [60]:
# examine the best model
print(grid.best_score_)
print(grid.best_params_)

0.945509586276
{'clf-svm__alpha': 0.001, 'tfidf__use_idf': False, 'vect__ngram_range': (1, 1)}


In [61]:
# view the results
pd.DataFrame(grid.cv_results_)[['mean_test_score', 'std_test_score', 'params']]

mean_test_score  std_test_score  \
0         0.894046        0.042985   
1         0.892028        0.041402   
2         0.914228        0.033435   
3         0.910192        0.036627   
4         0.930373        0.026970   
5         0.922301        0.023162   
6         0.945510        0.016387   
7         0.945510        0.013714   

                                              params  
0  {'clf-svm__alpha': 0.01, 'tfidf__use_idf': Tru...  
1  {'clf-svm__alpha': 0.01, 'tfidf__use_idf': Tru...  
2  {'clf-svm__alpha': 0.01, 'tfidf__use_idf': Fal...  
3  {'clf-svm__alpha': 0.01, 'tfidf__use_idf': Fal...  
4  {'clf-svm__alpha': 0.001, 'tfidf__use_idf': Tr...  
5  {'clf-svm__alpha': 0.001, 'tfidf__use_idf': Tr...  
6  {'clf-svm__alpha': 0.001, 'tfidf__use_idf': Fa...  
7  {'clf-svm__alpha': 0.001, 'tfidf__use_idf': Fa...