Classifier

In [2]:
import pandas as pd
import csv

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [6]:
df = pd.read_csv('new_articles_0.csv', decoding='utf-8')

TypeError: parser_f() got an unexpected keyword argument 'decoding'

In [11]:
df = pd.read_csv('Test.csv')

In [12]:
X = df['Article_content']
Y = df['type']

In [13]:
X = X.fillna("")

In [14]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
Y = le.fit_transform(Y.astype(str))


In [15]:
from sklearn.model_selection import cross_val_score

In [16]:
from sklearn.pipeline import Pipeline

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
text_clf_RandomForest = Pipeline([('vect', CountVectorizer()), ('tfidf', TfidfTransformer()), ('clf',  RandomForestClassifier(n_estimators=200,oob_score=True,random_state=100,n_jobs=-1,max_features=None,min_samples_leaf=50))])

calculate score for each CV split

In [19]:
scores5 = cross_val_score(text_clf_RandomForest, X, Y, cv=10, scoring='accuracy')

In [12]:
scores5.mean()
# 0.9979381443298969
# 0.997979797979798

0.997979797979798

cross-validated estimates for each input data point

In [20]:
from sklearn.model_selection import cross_val_predict

In [14]:
predictions = cross_val_predict(text_clf_RandomForest, X, Y, cv=10)

In [15]:
predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

To make predictions

In [21]:
# train the model using all the data
text_clf_RandomForest.fit(X, Y)

Pipeline(memory=None,
     steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip...imators=200, n_jobs=-1,
            oob_score=True, random_state=100, verbose=0, warm_start=False))])

Articles extracted from RSS

In [45]:
# import feedparser
# # RSS feed url
# url = 'http://www.dailymirror.lk/RSS_Feeds/breaking-news'
# feed = feedparser.parse(url)
# entries = feed['entries']
# from newspaper import Article
# articles = []
# for entry in entries:
#     url = entry['link']
#     article = Article(url)
#     article.download()
#     article.parse()
#     articles.append({
#         'Title': entry['title'].encode("utf-8"),
#         'Date': entry['published'].encode("utf-8"),
#         'Article_content': article.text.encode("utf-8"),
# #         article.nlp()
# #         'Summary': article.summary,
#         'Summary': entry['summary'],
# #         'Summary': 'summary',
#         'Link': entry['link'].encode("utf-8"),
#     })
# import re
# TAG_RE=re.compile(r'<[^>]+>')
# for article in articles:
#     summary = article['Summary']
#     pure_summary=TAG_RE.sub('',summary)
#     article['Summary']=pure_summary.encode("utf-8")
# import csv
# with open('Test_dataset_content_2.csv',mode='w') as csv_file:
#     fieldnames=['Title','Date','Article_content','Summary','Link']
#     writer=csv.DictWriter(csv_file,fieldnames=fieldnames)

#     writer.writeheader()
#     for article in articles:
#         writer.writerow({'Title':article['Title'],'Date':article['Date'],'Article_content':article['Article_content'],'Summary':article['Summary'],'Link':article['Link']})


In [49]:
import feedparser
# RSS feed url
url = 'http://www.dailymirror.lk/RSS_Feeds/breaking-news'
feed = feedparser.parse(url)
entries = feed['entries']
# print(entries)
from newspaper import Article
articles = []
for entry in entries:
    url = entry['link']
    article = Article(url)
    article.download()
    article.parse()
    articles.append({
        'Title': entry['title'],
        'Date': entry['published'],
        'Article_content': article.text,
#         article.nlp()
#         'Summary': article.summary,
        'Summary': entry['summary'],
#         'Summary': 'summary',
        'Link': entry['link'],
    })
import re
TAG_RE=re.compile(r'<[^>]+>')
for article in articles:
    summary = article['Summary']
    pure_summary=TAG_RE.sub('',summary)
    article['Summary']=pure_summary
import csv
with open('Test_dataset_content_2.csv',mode='w') as csv_file:
    fieldnames=['Title','Date','Article_content','Summary','Link']
    writer=csv.DictWriter(csv_file,fieldnames=fieldnames)

    writer.writeheader()
    for article in articles:
        writer.writerow({'Title':article['Title'].encode("utf-8"),'Date':article['Date'].encode("utf-8"),'Article_content':article['Article_content'].encode("utf-8"),'Summary':article['Summary'].encode("utf-8"),'Link':article['Link'].encode("utf-8")})


In [50]:
df_new = pd.read_csv('Test_dataset_content_2.csv', )

In [51]:
new_articles = df_new['Article_content']

In [52]:
df_new.shape

(20, 5)

In [53]:
new_articles = new_articles.fillna("")

Make Predictions

In [54]:
type_arr = text_clf_RandomForest.predict(new_articles)
print(type_arr)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [22]:
from mysql.connector import MySQLConnection, Error

In [23]:
config = {
  'user': 'root',
  'password': '',
  'host': '127.0.0.1',
  'database': 'dengue_sri_lanka',
  'raise_on_warnings': True
}

In [24]:
def insert_article(publication_date, title, content, summary, link):
    query = "INSERT IGNORE INTO news_articles(publication_date, title, content, summary, link) " \
            "VALUES(%s,%s,%s,%s,%s)"
    args = (publication_date, title, content, summary, link)
 
    try:
#         db_config = read_db_config()
        conn = MySQLConnection(**config)
 
        cursor = conn.cursor()
        cursor.execute(query, args)
 
#         if cursor.lastrowid:
#             print('last insert id', cursor.lastrowid)
#         else:
#             print('last insert id not found')
 
        conn.commit()
    except Error as error:
        print(error)
 
    finally:
        cursor.close()
        conn.close()

In [25]:
# for articles after the test dataset
df1 = pd.read_csv('new_articles.csv')
prev_articles = df1['Article_Content']
print(prev_articles.shape)
prev_articles = prev_articles.fillna("")
type_of_prev = text_clf_RandomForest.predict(prev_articles)
print(type_of_prev)

(30,)
[0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]


In [32]:
# fix the error: Incorrect string value ..............
# in db, make 'title' AND 'link', the unique index
index = 0;
for x in type_of_prev:
    if x==0: 
        insert_article(df1.iloc[index]['Date'], df1.iloc[index]['Title'], df1.iloc[index]['Article_Content'].encode("utf-8"), "", "")

    #         print(type_arr.index(x))
    index = index + 1

1366: Incorrect string value: '\xEF\xBF\xBDInt...' for column 'content' at row 1
1366: Incorrect string value: '\xEF\xBF\xBDs a...' for column 'content' at row 1
1366: Incorrect string value: '\xEF\xBF\xBDs\xEF\xBF...' for column 'content' at row 1
1366: Incorrect string value: '\xEF\xBF\xBDt l...' for column 'title' at row 1
1366: Incorrect string value: '\xEF\xBF\xBDs w...' for column 'content' at row 1
1366: Incorrect string value: '\xEF\xBF\xBDBlo...' for column 'content' at row 1
1366: Incorrect string value: '\xEF\xBF\xBD\xEF\xBF\xBD...' for column 'content' at row 1
1366: Incorrect string value: '\xEF\xBF\xBDOn ...' for column 'content' at row 1
1366: Incorrect string value: '\xEF\xBF\xBDs A...' for column 'title' at row 1
1366: Incorrect string value: '\xEF\xBF\xBDRs....' for column 'content' at row 1
1366: Incorrect string value: '\xEF\xBF\xBDthe...' for column 'content' at row 1
1366: Incorrect string value: '\xEF\xBF\xBDLan...' for column 'title' at row 1
1265: Data truncate

In [65]:
# extract articles with 0 as the result and update the db table (without duplicates)
index = 0;
for x in type_arr:
    if x==0: #change to 0
#         print(articles[index]['Title'])
#         print(articles[index]['Title'].decode("utf-8"))
#         insert_article(articles[index]['Date'].decode("utf-8"), articles[index]['Title'].decode("utf-8"), articles[index]['Article_content'].decode("utf-8"), articles[index]['Summary'].decode("utf-8"), articles[index]['Link'].decode("utf-8"))
        insert_article(articles[index]['Date'], articles[index]['Title'], articles[index]['Article_content'], articles[index]['Summary'], articles[index]['Link'])

    #         print(type_arr.index(x))
    index = index + 1

In [ ]:
# the code for info extraction (use above table and extract data from that and store in respective tables)